#!/bin/ksh

last=$(basename $(cat /etc/iked.conf | tail -n 1 | awk '{print $2}' | sed 's/"//g') | sed 's/iked.conf.//')
filename=$(ls *"$last")
sed -i "/$last/d" /etc/iked.conf
rm -rf "/etc/$filename"
rcctl restart iked
for file in $(grep $last * | grep hostname | cut -d : -f1); do
	echo $file
	interface=$(echo $file | cut -d . -f2)
	if [ "$interface" == "gre"? ]; then
		ospfinterface=$interface
	fi
	ifconfig $interface destroy
	rm -rf $file
done
sed -i "/interface $ospfinterface/,/}/d" /etc/ospfd.conf
rcctl restart ospfd
