#!/bin/bash

tmpdir=$(mktemp -d)

if [[ $# -eq 0 ]];then
	print "No Arguments"
	exit
fi

pk12=$(basename $1)
publichost=$(echo $pk12 | sed 's/.p12//')
publichostname=$(echo $publichost | cut -d . -f1)
domainname=$(echo $publichost | sed "s/$publichostname.//")


for a in $(dig ipsec20591.$domainname TXT +short @8.8.8.8 | sed "s/\"//g" | tr \; '\n' | sed '$d'); do
	b=$(echo $a | cut -d : -f1)
	if [[ "$b" -eq "$publichostname" ]]; then
		srcid=$(echo $a | cut -d : -f2)
	fi
done


openssl pkcs12 -nodes -in $1 -nocerts -passin pass:123456789 -passout pass:123456789 -out "$tmpdir/local.key"
openssl pkcs12 -nodes -in $1 -clcerts -nokeys -passin pass:123456789 -passout pass:123456789 -out "$tmpdir/new.crt"
openssl x509 -pubkey -noout -passin pass:123456789 -in "$tmpdir/new.crt"  > src/etc/iked/pubkeys/ufqdn/"$srcid@ca.$domainname"

rm -rf $tmpdir

echo -e "$srcid@ca.$domainname created please update repository and all the others Openbsd hosts"
