#!/bin/ksh

#	$Telecomlobby: setup_node,v 0.1 11/3/2021 21:01:04 taglio$
#

function pkg {
	phase = $1

	case $phase in
		"shell")
			echo "adding shell related packages"
			pkg_add colorls nano wget git;;
	esac
}

echo "changing installurl"
echo "https://cdn.openbsd.org/pub/OpenBSD" > /etc/installurl
echo "adding packages basic shell packages"
pkg "shell"

