#!/bin/ksh

set -e
set -o errexit
set -o nounset

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/Bin
BACKUPS="/root/Backups"

uid=$(id -u)
datarelease=$(date +"%d%m%Y%H%m%S")




function backup {
	CURRENTBACKUP="$BACKUPS/$datarelease"
	mkdir -p "$CURRENTBACKUP/$1/"
	case $1 in
		"etc")
			tar -cvf "$CURRENTBACKUP/$1/etc.tar" /etc
		;;
	esac
}


if [[ $uid -ne 0 ]]; then
	print $0 "you've got to run $0 as UID=0 \n"
	exit 1
fi

nohup backup "etc" & > /tmp/nohup

if [[ -z "${1}" ]]; then
	last=$(basename $(cat /etc/iked.conf | grep "iked.conf." | tail -n 1 | awk '{print $2}' | sed 's/"//g' | sed 's/iked.conf.//'))
elif [[ ! -z "${1}" && "${1}" == gre*[0-9] ]]; then
	last=$(ifconfig "${1}" | grep description | awk '{print $2}')
fi
publichostname=$(echo $last | cut -d . -f1)
domainname=$(echo $last | sed "s/$publichostname.//")
pip=$(dig A "${last}" +short)

for a in $(dig ipsec20591.$domainname TXT +short | sed "s/\"//g" | tr \; '\n' | sed '$d'); do
	b=$(echo $a | cut -d : -f1)
	if [[ "${b}" == "${publichostname}" ]]; then
		srcid=$(echo $a | cut -d : -f2)
	fi
done

filename=$(find /etc -name "*$last" -maxdepth 1 -type f)
sed -i "/$last/d" /etc/iked.conf
/bin/rm -r "$filename"
rcctl restart iked
for file in $(grep "$last" /etc/* | grep hostname | cut -d : -f1); do
	interface=$(echo $file | cut -d . -f2)
	if [[ $interface == gre*[0-9] ]]; then
		ospfinterface=$interface
		ifconfig $interface destroy
	elif [[ $interface == enc*[0-9] ]]; then
		ifconfig $interface description ""
	fi
	/bin/rm -r $file
done
pubkey="$srcid@ca.$domainname"
sed -i "/interface $ospfinterface/,/}/d" /etc/ospfd.conf
sed -i "/$ospfinterface/d" /etc/pf.conf.macro.gre.tag.in
sed -i "/$pip/d" /etc/pf.conf.table.ipsec
/sbin/pfctl -t ipsec -T kill
/sbin/pfctl -t ipsec -T add -f /etc/pf.conf.table.ipsec
[[ -e "/etc/iked/pubkeys/ufqdn/${pubkey}" ]] && /bin/rm -r "/etc/iked/pubkeys/ufqdn/${pubkey}"
[[ -e "/etc/iked/certs/${last}.crt" ]] && /bin/rm -r "/etc/iked/certs/${last}.crt"
pfctl -f /etc/pf.conf
nohup rcctl restart ospfd &> /dev/null
exit
